### ISSUE TITLE
add Synchronisation feature/dialog

### ISSUE THREAD

**Issue by WolfgangFahl** [WolfgangFahl/pyOnlineSpreadSheetEditing#41]
On (multiple) row select and click of "sync button".

Show list of two cards side by side  with the properties of the two synchronisation partners

E.g. 

- gsimport versus wiki
- gsimport versus wikidata
- wiki versus wikidata

allow option per attribute:
←
→
✅
❌

Example (as table)

|Property| wiki| ⇆ |wikidata|
|---|---|---|---| 
|Label: |Xiao Liu| ✅ |Xiao Liu|
|Description:||← |Researcher ORCID(0000-0002-9226-4569)|
|ORCID: |-| ←| 0000-0002-9226-4569|
|Research Gate:| Xiao_Liu114| →||

Potential Action: ⇆ ← → ☐

There should be a potential default for the whole card set. So all properties get to ⇆ ← → ☐ (see y-principle-gen)
The status should be marked e.g. with colors red for missing or error, green for same, blue for new 

Conflicts shall also be marked with ⇆❌ and same entries  ⇆✅ sync entries should have the arrow ☐✅

There should be a button on top with a dry run selector that actually does the sync for all items and shows some kind of progress and debug and profile results. (Parallel handling possible ...)

Potentially there is a need for  extra details if the data has extra information such as a  language/type ...  this might need extra way of handlingt with another column or some popup or show/hide effect.

**Comment by tholzheim** [comment]
With our mapping schema we allow Qids and labels as inputs which are during the upload matched against the corresponding items. For the value comparison this means that we either need to normalize the records or convert them to an object that can evaluate the equality a given Qid and label.
![image](https://user-images.githubusercontent.com/45004115/217097402-6a7dac2d-c929-471f-8181-460ea01f78fc.png)
